#!/bin/bash

case "$1" in
  'ima')
    shift
    docker images $@
    ;;
  'ins')
    shift
    docker inspect $@
    ;;
  'res')
    shift
    docker restart $@
    ;;
  'sta')
    shift
    docker start $@
    ;;
  'cl')
    if [ "$2" == '-f' ]; then
      docker rm -f `docker ps -a -q`
    else
      docker rm `docker ps -a -q`
    fi
    ;;
  'cli')
    docker rmi $(docker images -a | awk '/^<none>/ { print $3 }')
    ;;
  *)
    docker $@
    ;;
esac
