#!/bin/bash

if [ $# -ne 3 ]; then
  echo "Usage: $1 IMAGE_NAME SRC_PATH DEST_PATH"
  exit 1
fi

# container image name
image_name=$1

# Path of source file in container image
src_path=$2

# Destination path in local machine
dest_path=$3

container_name=dcp-$$

id=$(docker run -d --name ${container_name} --entrypoint='/bin/cat /dev/null' ${image_name} 2>/dev/null)

if [ "${id}" == "" ]; then
  exit 1
fi

docker cp ${id}:${src_path} ${dest_path}; docker rm -f ${id} >/dev/null
