#!/bin/bash

# Copy a file or directory from an image

if [[ $# != 3 ]]; then
  echo "Usage: $1 IMAGE_NAME SRC_PATH DEST_PATH"
  exit 1
fi

image_name=$1
src_path=$2
dest_path=$3
container_name=docker-cpi-$$

id=$(docker run -d --name ${container_name} --entrypoint='/dev/null' ${image_name} 2>/dev/null)

if [ "${id}" == "" ]; then
  exit 1
fi

docker cp -a ${id}:${src_path} ${dest_path}
docker rm -f ${id} >/dev/null
