#!/bin/bash

case "$1" in
  's')
    shift
    git status $@
    ;;
  'b')
    shift
    git branch $@
    ;;
  'c')
    shift
    git commit $@
    ;;
  'ca')
    shift
    git commit --amend $@
    ;;
  'co')
    shift
    git checkout $@
    ;;
  'cob')
    shift
    git checkout -b $@
    ;;
  'd')
    shift
    git diff $@
    ;;
  'dc')
    shift
    git diff --cached $@
    ;;
  'pb')
    git branch | peco | xargs git checkout
    ;;
  'pd')
    git log --oneline --branches | peco | awk '{print $1}' | xargs -I{} git diff {}^..{}
    ;;
  'pch')
    shift
    git log --oneline --branches | peco | awk '{print $1}' | xargs git cherry-pick $@
    ;;
  'pe')
    git status -s | peco | awk '{ print $2 }' | xargs $EDITOR
    ;;
  *)
    git $@
    ;;
esac
