#!/bin/bash

usage_exit() {
  echo "Usage: $0 [-q] command" 1>&2
  exit 1
}

while getopts q OPT; do
  case $OPT in
    q)  FLAG_QUIET=1
        ;;
    \?) usage_exit
        ;;
  esac
done

shift $((OPTIND - 1))

if [ "$1" == "" ]; then
  usage_exit
  exit 1
fi

command=$1

if which $command >/dev/null 2>&1; then
  exit 0
fi

if [ "$FLAG_QUIET" != 1 ]; then
  echo "$command: not found"
fi

exit 1
