#!/bin/bash

spinner() {
  local pid="$1"
  if [ "$1" == "" ]; then
    echo "Please specify PID" 1>&2
    return 1
  fi
  local delay=0.75
  local spinstr='|/-\'
  while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
    local temp=${spinstr#?}
    printf " [%c]  " "$spinstr"
    local spinstr=$temp${spinstr%"$temp"}
    sleep $delay
    printf "\b\b\b\b\b\b"
  done
  printf "    \b\b\b\b"
}

spinner "$1"
