---
driver:
  name: docker

driver_config:
  require_chef_omnibus: false
  provision_command:
    - curl -L https://www.opscode.com/chef/install.sh | bash
    - apt-get update
    - apt-get install -y vim

provisioner:
  name: chef_zero

platforms:
  - name: debian-latest
